Ecommerce_base/urls.py
# Ecommerce_base\urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name = "Ecommerce_base"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Ecommerce_home.urls")),
    path("users/", include("Ecommerce_users.urls", namespace="Ecommerce_users")),
    path("profiles/", include("Ecommerce_profiles.urls")),
    path(
        "products/", include("Ecommerce_products.urls", namespace="Ecommerce_products")
    ),
    path("cart/", include("Ecommerce_cart.urls", namespace="Ecommerce_cart")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce_cart/urls.py
# Ecommerce_cart\urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "Ecommerce_cart"

urlpatterns = [
    path("", views.view_cart, name="view_cart"),
    path("add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("login_or_register/", views.login_or_register, name="login_or_register"),
    path(
        "create-checkout-session/",
        views.create_checkout_session,
        name="create_checkout_session",
    ),
    path("success/", views.payment_success, name="payment_success"),
    path("cancel/", views.payment_cancel, name="payment_cancel"),
    path(
        "update-shipping-option",
        views.update_shipping_option,
        name="update_shipping_option",
    ),
    path("order-history/", views.order_history, name="order_history"),
    path("order/<int:order_id>/", views.order_detail, name="order_detail"),
    path("museum-entry/<int:order_id>/", views.museum_entry, name="museum_entry"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce_users/urls.py
# Ecommerce_users\urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from Ecommerce_profiles.views import user_profile, edit_user_profile

app_name = "Ecommerce_users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("logout/confirmation/", views.logout_confirmation, name="logout_confirmation"),
    path("logout/", views.logout_view, name="logout"),
    path("login/", views.login_view, name="login"),
    # Password reset URLs
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("password_reset/done/", views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Profile URL kept here to keep the url as 'users/profile'
    path("profile/", user_profile, name="profile"),
    path("profile/edit/", edit_user_profile, name="edit_user_profile"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart/add_to_cart.html
<!-- templates\cart\add_to_cart.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}

<style>
    .opening-closing-times-box {
        display: flex !important;
        /* flex-wrap: wrap; */

    }

    @media only screen and (max-width: 767px),
    only screen and (max-device-width: 767px) {

        .opening-closing-times-box {
            flex-wrap: wrap;

        }
    }
</style>


<div class="smooth-scroll">
    <div class="section-wrapper" data-scroll-section>
        <!-- SEARCH BOX -->
        {% include 'common_includes/search.html' %}
        <!-- SIDE BOX -->
        {% include 'common_includes/side-box.html' %}
        <!-- NAV BAR -->
        {% include 'common_includes/nav-bar.html' %}

        <section class="content-section" data-background="#fffbf7">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="side-content left">
                            <h2>{{ product.name }}</h2>
                            <p>{{ product.description }}</p>
                        </div>
                        <!-- end side-content -->
                        <div class="clearfix spacing-50"></div>
                        <div class="side-icon-list">
                            <ul class="opening-closing-times-box">
                                <li>
                                    <div class="content">
                                        <h5>Opening</h5>
                                        <p>{{ product.opening_time|date:"l, F dS" }}<br>
                                            {{ product.opening_time|time:"fA" }}
                                        </p>
                                    </div>

                                    <!-- end content -->
                                </li>
                                <li>
                                    <div class="content">
                                        <h5>Closing</h5>
                                        <p>{{ product.closing_time|date:"l, F dS" }}<br>
                                            {{ product.closing_time|time:"fA" }}
                                        </p>
                                    </div>

                                    <!-- end content -->
                                </li>
                            </ul>
                        </div>
                        <!-- end side-icon-list -->
                    </div>
                    <!-- end col-6 -->
                    <div class="col-lg-6">
                        <figure class="side-image" data-scroll data-scroll-speed="1"> <img
                                src="{% static 'images/side-imag01.jpg' %}" alt="Image"> </figure>
                    </div>
                    <!-- end col-6 -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </section>
        <!-- end content-section -->
        <section class="content-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="contact-box">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.museum_location }}</p>
                            <p>£{{ product.price }}</p>
                        </div>
                        <div class="contact-box">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Add to Cart</button>
                            </form>
                        </div>
                        <!-- end contact-box -->
                        <div class="clearfix spacing-50"></div>
                    </div>
                    <!-- end col-5 -->
                    <div class="col-lg-7">
                        <div class="side-list">
                            <ul>
                                <li>
                                    Secure your ticket by completing your purchase.
                                </li>
                                <li>
                                    Keep an eye on your inbox for the confirmation email.</li>
                                <li>
                                    Save and have your QR code readily accessible.
                                </li>
                                <li>
                                    On the event day, present your QR code to the staff at the entrance for seamless
                                    entry.
                                </li>
                            </ul>
                        </div>
                        <!-- end side-list -->
                    </div>
                    <!-- end col-7 -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </section>
        <!-- end content-section -->


    </div>
</div>


{% endblock %}

templates/cart/cart_detail.html
<!-- templates\cart\cart_detail.html -->
{% extends "base.html" %}
{% load static %}
{% load cart_extras %}

{% block content %}
<style>
    .checkout-btn {
        height: 70px;
        display: inline-block;
        font-size: 24px;
        font-weight: 300;
        color: #000;
        background: #94ffc4;
        border: none;
        padding: 0 50px;
        transition: 0.3s;
        width: 50%;
    }
    .checkout-btn:hover {
        background: #000;
        color: #fff;
    }
</style>


<!-- end page-transition -->
<div class="smooth-scroll">
    <div class="section-wrapper" data-scroll-section>
        <!-- SEARCH BOX -->
        {% include 'common_includes/search.html' %}
        <!-- SIDE BOX -->
        {% include 'common_includes/side-box.html' %}
        <!-- NAV BAR -->
        {% include 'common_includes/nav-bar.html' %}
        <section class="content-section" data-background="#fffbf7">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <figure>
                                <img src="{% static 'images/title-shape.png' %}" alt="Image">
                            </figure>
                            {% if cart and cart.items.count > 0 %}
                            {% for item in cart.items.all %}
                            <h2>{{ item.product.name }}</h2>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <!-- end section-title -->
                    </div>
                    <!-- end col-12 -->
                    <div class="col-lg-12 text-center d-flex justify-content-center">
                        <div class="contact-box px-5" style="width: 75%;">
                            <h6>Seamless Ticket Purchase and Entry Instructions</h6>
                            <p>
                                After clicking 'Buy Tickets,' you'll be directed to the Stripe payment system. Once your
                                payment is successfully processed, you'll receive a special QR code via email. Please
                                ensure you provide a valid email address that you can access, as you'll need to keep
                                this QR code for entry.
                            </p>
                        </div>

                    </div>
                    <div class="clearfix spacing-50"></div>

                    <button class="checkout-btn" id="checkout-button">
                        BUY TICKET
                    </button>
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </section>


        <script src="https://js.stripe.com/v3/"></script>
        <script>
            var stripe = Stripe('{{ stripe_public_key }}');

            document.querySelector("#checkout-button").addEventListener("click", function () {
                fetch("{% url 'Ecommerce_cart:create_checkout_session' %}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                        "Content-Type": "application/json",
                    },
                })
                    .then((response) => response.json())
                    .then((session) => {
                        return stripe.redirectToCheckout({ sessionId: session.id });
                    })
                    .then((result) => {
                        if (result.error) {
                            alert(result.error.message);
                        }
                    })
                    .catch((error) => {
                        console.error("Error:", error);
                    });
            });

            document.querySelector("#shipping-form").addEventListener("submit", function (event) {
                event.preventDefault();
                var shippingOptionId = document.querySelector("#shipping-select").value;
                fetch("{% url 'Ecommerce_cart:update_shipping_option' %}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({ shipping_option: shippingOptionId }),
                })
                    .then((response) => response.json())
                    .then((data) => {
                        location.reload();
                    })
                    .catch((error) => {
                        console.error("Error:", error);
                    });
            });
        </script>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <h6 class="widget-title">About Museum</h6>
                        <ul class="footer-menu">
                            <li><a href="#">About us </a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">National work</a></li>
                            <li><a href="#">International work</a></li>
                        </ul>
                    </div>
                    <!-- end col-4 -->
                    <div class="col-lg-4 col-md-6">
                        <h6 class="widget-title">Connect Us</h6>
                        <ul class="social-media">
                            <li><a href="#"><i class="fab fa-facebook-f"></i> /wandau-uk</a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i> /wandau-museum</a></li>
                            <li><a href="#"><i class="fab fa-youtube"></i> /wandau-tv</a></li>
                        </ul>
                    </div>
                    <!-- end col-4 -->
                    <div class="col-lg-4">
                        <h6 class="widget-title">Visit Us Now</h6>
                        <address class="address">
                            Cromwell Road New Town SW7 <strong>London - England</strong> <i
                                class="fas fa-info-circle"></i> +44 (0)20 7942 2000
                        </address>
                    </div>
                    <!-- end col-4 -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
            <div class="footer-bottom">
                <div class="container"> <span class="copyright">© 2023 Wandau | Art & History Museum</span> <span
                        class="creation">Site created by <a href="#">themezinho</a></span> </div>
                <!-- end container -->
            </div>
            <!-- end footer-bottom -->
        </footer>
        <!-- end footer -->
    </div>
</div>


{% endblock %}

templates/cart/login_or_register.html
<!-- templates\cart\login_or_register.html -->
{% extends "base.html" %}

{% block content %}
<h2>Login or Register</h2>
<p>You need to be logged in to add items to your cart. Please
    <a href="{% url 'Ecommerce_users:login' %}">login</a> or
    <a href="{% url 'Ecommerce_users:register' %}">register</a>
    to continue.
</p>
{% endblock %}

templates/cart/museum_entry.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Museum Entry for Order #{{ order.id }}</h1>
<p><strong>Name:</strong> {{ order.user.username }}</p>
<p><strong>Email:</strong> {{ order.user.email }}</p>
<p><strong>Shipping Address:</strong> {{ order.shipping_address }}</p>
<h2>Purchased Products:</h2>
<ul>
    {% for item in order_items %}
        <li>{{ item.quantity }} x {{ item.product.name }}</li>
    {% endfor %}
</ul>{% endblock %}

templates/cart/order_detail.html
<!-- templates\cart\order_detail.html -->
{% extends "base.html" %}

{% block content %}
<h2>Order #{{ order.id }}</h2>
<p>Placed on: {{ order.created_at|date:"d M Y" }}</p>
<p>Total Amount: £{{ order.total_amount }}</p>

{% if order.shipping_option %}
<p>Shipping Option: {{ order.shipping_option.name }} - £{{ order.shipping_option.price }}</p>
{% else %}
<p>No shipping option selected.</p>
{% endif %}

<p>Shipping Address:</p>
<p>{{ order.shipping_address }}</p>

<h3>Order Items:</h3>
<ul>
    {% for item in order_items %}
    <li>
        {{ item.product.name }} (x{{ item.quantity }}) - £{{ item.price }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'Ecommerce_cart:order_history' %}">Back to Order History</a>
{% endblock %}

templates/cart/order_history.html
{% extends "base.html" %}

{% block content %}
<h2>Your Order History</h2>

{% if orders %}
    <ul>
        {% for order in orders %}
            <li>
                <a href="{% url 'Ecommerce_cart:order_detail' order.id %}">Order #{{ order.id }} - {{ order.created_at|date:"d M Y" }} - £{{ order.total_amount }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>You have no orders yet.</p>
{% endif %}
{% endblock %}

templates/cart/payment_success.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<h1>Payment Successful.</h1>
<a href="/">Home</a>
{% endblock %}